# Generated by Django 4.1.7 on 2023-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=8)),
                ('file_type', models.TextField(blank=True, null=True)),
                ('docfile', models.FileField(upload_to='csvtonestedjson/Input')),
            ],
        ),
    ]
